<?php
//Generated by Jordan Frisay Himawan

namespace app\models;

use Yii;


/**
 * This is the model class for table "customer".
 *
 * @property int $id
 * @property string $nama
 * @property int|null $email
 * @property int $user_id
 *
 * @property Order[] $orders
 * @property User $user
 */
class Customer extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'customer';
    }

    // TODO: Minggu 6 latihan 3
    public function beforeSave($insert)
    {
        if ($insert) {
            $this->user_id = Yii::$app->user->id;
        }
        return parent::beforeSave($insert);
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['nama'], 'required'],
            [['email', 'user_id'], 'string', 'max' => 255],
            [['nama'], 'string', 'max' => 255],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::class, 'targetAttribute' => ['user_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nama' => 'Nama',
            'email' => 'Email',
            'user_id' => 'User ID',
        ];
    }

    /**
     * Gets query for [[Orders]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getOrders()
    {
        return $this->hasMany(Order::class, ['customer_id' => 'id']);
    }

    /**
     * Gets query for [[User]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::class, ['id' => 'user_id']);
    }

    // TODO: Minggu 6 latihan 3
    public function beforeValidate()
    {
        if (!$this->isNewRecord && $this->user_id !== Yii::$app->user->identity->id) {
            $this->addError('user_id', 'You can only have one customer.');
            return false;
        }
    return parent::beforeValidate();
    }
}
